# category:
#   - tag

# You can add categories or tags,
# they will be loaded into the database when running 'rake admin:categories:create'.
# You can't delete or change them from here.

programming languages:
  - C
  - C++
  - C#
  - Clojure
  - Crystal
  - Elixir
  - Elm
  - Erlang
  - F#
  - Go
  - Groovy
  - Haskell
  - Idris
  - Java
  - JavaScript+
  - Julia
  - Kotlin
  - Lisp
  - Lua
  - Objective-C
  - OCaml
  - Perl
  - PHP
  - Pony
  - Prolog
  - Python
  - R
  - Ruby
  - Rust
  - Scala
  - Swift

languages:
  - English
  - German
  - French
  - Spanish
  - Japanese
  - Chinese
  - Russian
  - Portuguese
  - Polish

fields of interest:
  - Math
  - Biology
